# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/andrey/project/znak/ConsoleWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConsoleWindow(object):
    def setupUi(self, ConsoleWindow):
        ConsoleWindow.setObjectName("ConsoleWindow")
        ConsoleWindow.resize(562, 379)
        self.text = QtWidgets.QTextEdit(ConsoleWindow)
        self.text.setGeometry(QtCore.QRect(10, 50, 541, 321))
        self.text.setMinimumSize(QtCore.QSize(100, 100))
        self.text.setBaseSize(QtCore.QSize(300, 200))
        self.text.setReadOnly(True)
        self.text.setObjectName("text")
        self.level = QtWidgets.QComboBox(ConsoleWindow)
        self.level.setGeometry(QtCore.QRect(120, 15, 76, 24))
        self.level.setObjectName("level")
        self.level.addItem("")
        self.level.addItem("")
        self.level.addItem("")
        self.level.addItem("")
        self.label = QtWidgets.QLabel(ConsoleWindow)
        self.label.setGeometry(QtCore.QRect(20, 20, 58, 16))
        self.label.setObjectName("label")

        self.retranslateUi(ConsoleWindow)
        QtCore.QMetaObject.connectSlotsByName(ConsoleWindow)

    def retranslateUi(self, ConsoleWindow):
        _translate = QtCore.QCoreApplication.translate
        ConsoleWindow.setWindowTitle(_translate("ConsoleWindow", "Form"))
        self.level.setItemText(0, _translate("ConsoleWindow", "INFO"))
        self.level.setItemText(1, _translate("ConsoleWindow", "DEBUG"))
        self.level.setItemText(2, _translate("ConsoleWindow", "WARNING"))
        self.level.setItemText(3, _translate("ConsoleWindow", "ERROR"))
        self.label.setText(_translate("ConsoleWindow", "Уровень"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConsoleWindow = QtWidgets.QWidget()
    ui = Ui_ConsoleWindow()
    ui.setupUi(ConsoleWindow)
    ConsoleWindow.show()
    sys.exit(app.exec_())
