# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/andrey/project/znak/ConsoleWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConsoleWindow(object):
    def setupUi(self, ConsoleWindow):
        ConsoleWindow.setObjectName("ConsoleWindow")
        ConsoleWindow.resize(473, 293)
        self.textBrowser = QtWidgets.QTextBrowser(ConsoleWindow)
        self.textBrowser.setGeometry(QtCore.QRect(0, 10, 471, 271))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(ConsoleWindow)
        QtCore.QMetaObject.connectSlotsByName(ConsoleWindow)

    def retranslateUi(self, ConsoleWindow):
        _translate = QtCore.QCoreApplication.translate
        ConsoleWindow.setWindowTitle(_translate("ConsoleWindow", "Консоль"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConsoleWindow = QtWidgets.QWidget()
    ui = Ui_ConsoleWindow()
    ui.setupUi(ConsoleWindow)
    ConsoleWindow.show()
    sys.exit(app.exec_())
