# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/andrey/project/znak/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.mdiArea = QtWidgets.QMdiArea(self.centralWidget)
        self.mdiArea.setGeometry(QtCore.QRect(40, 50, 200, 160))
        self.mdiArea.setObjectName("mdiArea")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menu)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menu)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menuBar)
        self.actExit = QtWidgets.QAction(MainWindow)
        self.actExit.setObjectName("actExit")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setCheckable(True)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setCheckable(True)
        self.action_4.setObjectName("action_4")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.actOptions = QtWidgets.QAction(MainWindow)
        self.actOptions.setObjectName("actOptions")
        self.actConsole = QtWidgets.QAction(MainWindow)
        self.actConsole.setObjectName("actConsole")
        self.actCreateDatabase = QtWidgets.QAction(MainWindow)
        self.actCreateDatabase.setObjectName("actCreateDatabase")
        self.actChangeDatabase = QtWidgets.QAction(MainWindow)
        self.actChangeDatabase.setObjectName("actChangeDatabase")
        self.menu_2.addAction(self.action_3)
        self.menu_2.addAction(self.action_4)
        self.menu_3.addAction(self.actCreateDatabase)
        self.menu_3.addAction(self.actChangeDatabase)
        self.menu.addAction(self.menu_2.menuAction())
        self.menu.addAction(self.menu_3.menuAction())
        self.menu.addAction(self.actOptions)
        self.menu.addAction(self.actConsole)
        self.menu.addAction(self.actExit)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Сменить источник сырья"))
        self.menu_3.setTitle(_translate("MainWindow", "Базы данных"))
        self.actExit.setText(_translate("MainWindow", "Выход"))
        self.action_3.setText(_translate("MainWindow", "Давальческое сырье"))
        self.action_4.setText(_translate("MainWindow", "Собственное сырье"))
        self.action_6.setText(_translate("MainWindow", "Архивировать базу данных..."))
        self.action_7.setText(_translate("MainWindow", "Восстановить базу данных..."))
        self.actOptions.setText(_translate("MainWindow", "Настройки..."))
        self.actConsole.setText(_translate("MainWindow", "Консоль логов"))
        self.actCreateDatabase.setText(_translate("MainWindow", "Создать новую..."))
        self.actChangeDatabase.setText(_translate("MainWindow", "Сменить..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
