# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/andrey/project/znak/OptionsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OptionsWindow(object):
    def setupUi(self, OptionsWindow):
        OptionsWindow.setObjectName("OptionsWindow")
        OptionsWindow.resize(678, 432)
        OptionsWindow.setSizeGripEnabled(True)
        self.layoutWidget = QtWidgets.QWidget(OptionsWindow)
        self.layoutWidget.setGeometry(QtCore.QRect(160, 380, 351, 33))
        self.layoutWidget.setObjectName("layoutWidget")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem = QtWidgets.QSpacerItem(71, 31, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.okButton = QtWidgets.QPushButton(self.layoutWidget)
        self.okButton.setObjectName("okButton")
        self.hboxlayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(self.layoutWidget)
        self.cancelButton.setObjectName("cancelButton")
        self.hboxlayout.addWidget(self.cancelButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.groupBox = QtWidgets.QGroupBox(OptionsWindow)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 341, 161))
        self.groupBox.setObjectName("groupBox")

        self.retranslateUi(OptionsWindow)
        self.okButton.clicked.connect(OptionsWindow.accept)
        self.cancelButton.clicked.connect(OptionsWindow.reject)
        QtCore.QMetaObject.connectSlotsByName(OptionsWindow)

    def retranslateUi(self, OptionsWindow):
        _translate = QtCore.QCoreApplication.translate
        OptionsWindow.setWindowTitle(_translate("OptionsWindow", "Настройки"))
        self.okButton.setText(_translate("OptionsWindow", "&OK"))
        self.cancelButton.setText(_translate("OptionsWindow", "&Cancel"))
        self.groupBox.setTitle(_translate("OptionsWindow", "Ведение логов"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OptionsWindow = QtWidgets.QDialog()
    ui = Ui_OptionsWindow()
    ui.setupUi(OptionsWindow)
    OptionsWindow.show()
    sys.exit(app.exec_())
