# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OtgruzkaWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OtgruzkaWindow(object):
    def setupUi(self, OtgruzkaWindow):
        OtgruzkaWindow.setObjectName("OtgruzkaWindow")
        OtgruzkaWindow.resize(585, 418)
        self.table = QtWidgets.QTableView(OtgruzkaWindow)
        self.table.setGeometry(QtCore.QRect(10, 40, 541, 361))
        self.table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table.setSortingEnabled(True)
        self.table.setObjectName("table")
        self.model = QtWidgets.QComboBox(OtgruzkaWindow)
        self.model.setGeometry(QtCore.QRect(10, 10, 111, 24))
        self.model.setObjectName("model")
        self.size = QtWidgets.QComboBox(OtgruzkaWindow)
        self.size.setGeometry(QtCore.QRect(120, 10, 61, 24))
        self.size.setObjectName("size")
        self.source = QtWidgets.QComboBox(OtgruzkaWindow)
        self.source.setGeometry(QtCore.QRect(180, 10, 51, 24))
        self.source.setObjectName("source")
        self.source.addItem("")
        self.source.setItemText(0, "")
        self.source.addItem("")
        self.source.addItem("")
        self.count = QtWidgets.QSpinBox(OtgruzkaWindow)
        self.count.setGeometry(QtCore.QRect(230, 10, 46, 26))
        self.count.setObjectName("count")
        self.btnAdd = QtWidgets.QPushButton(OtgruzkaWindow)
        self.btnAdd.setGeometry(QtCore.QRect(280, 10, 31, 28))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btnAdd.setFont(font)
        self.btnAdd.setObjectName("btnAdd")
        self.btnDelete = QtWidgets.QPushButton(OtgruzkaWindow)
        self.btnDelete.setGeometry(QtCore.QRect(310, 10, 31, 28))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btnDelete.setFont(font)
        self.btnDelete.setObjectName("btnDelete")
        self.prn = QtWidgets.QPushButton(OtgruzkaWindow)
        self.prn.setGeometry(QtCore.QRect(340, 10, 51, 28))
        self.prn.setObjectName("prn")

        self.retranslateUi(OtgruzkaWindow)
        QtCore.QMetaObject.connectSlotsByName(OtgruzkaWindow)

    def retranslateUi(self, OtgruzkaWindow):
        _translate = QtCore.QCoreApplication.translate
        OtgruzkaWindow.setWindowTitle(_translate("OtgruzkaWindow", "Form"))
        self.source.setItemText(1, _translate("OtgruzkaWindow", "НС"))
        self.source.setItemText(2, _translate("OtgruzkaWindow", "ДС"))
        self.btnAdd.setText(_translate("OtgruzkaWindow", "+"))
        self.btnDelete.setText(_translate("OtgruzkaWindow", "-"))
        self.prn.setText(_translate("OtgruzkaWindow", "Печать"))
