# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/andrey/project/znak/OtgruzkaWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OtgruzkaWindow(object):
    def setupUi(self, OtgruzkaWindow):
        OtgruzkaWindow.setObjectName("OtgruzkaWindow")
        OtgruzkaWindow.resize(585, 418)
        self.table = QtWidgets.QTableView(OtgruzkaWindow)
        self.table.setGeometry(QtCore.QRect(20, 30, 541, 371))
        self.table.setObjectName("table")

        self.retranslateUi(OtgruzkaWindow)
        QtCore.QMetaObject.connectSlotsByName(OtgruzkaWindow)

    def retranslateUi(self, OtgruzkaWindow):
        _translate = QtCore.QCoreApplication.translate
        OtgruzkaWindow.setWindowTitle(_translate("OtgruzkaWindow", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OtgruzkaWindow = QtWidgets.QWidget()
    ui = Ui_OtgruzkaWindow()
    ui.setupUi(OtgruzkaWindow)
    OtgruzkaWindow.show()
    sys.exit(app.exec_())
