# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/andrey/project/znak/ScanCodesWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScanCodesWindow(object):
    def setupUi(self, ScanCodesWindow):
        ScanCodesWindow.setObjectName("ScanCodesWindow")
        ScanCodesWindow.resize(301, 311)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ScanCodesWindow.sizePolicy().hasHeightForWidth())
        ScanCodesWindow.setSizePolicy(sizePolicy)
        ScanCodesWindow.setBaseSize(QtCore.QSize(400, 300))
        self.chooseFiles = QtWidgets.QPushButton(ScanCodesWindow)
        self.chooseFiles.setGeometry(QtCore.QRect(20, 20, 261, 28))
        self.chooseFiles.setObjectName("chooseFiles")
        self.label = QtWidgets.QLabel(ScanCodesWindow)
        self.label.setGeometry(QtCore.QRect(20, 70, 301, 16))
        self.label.setObjectName("label")
        self.source = QtWidgets.QComboBox(ScanCodesWindow)
        self.source.setGeometry(QtCore.QRect(140, 65, 141, 24))
        self.source.setObjectName("source")
        self.source.addItem("")
        self.source.setItemText(0, "")
        self.source.addItem("")
        self.source.addItem("")
        self.scan = QtWidgets.QPushButton(ScanCodesWindow)
        self.scan.setGeometry(QtCore.QRect(20, 260, 251, 28))
        self.scan.setObjectName("scan")
        self.textEdit = QtWidgets.QTextEdit(ScanCodesWindow)
        self.textEdit.setGeometry(QtCore.QRect(10, 100, 271, 151))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(ScanCodesWindow)
        QtCore.QMetaObject.connectSlotsByName(ScanCodesWindow)

    def retranslateUi(self, ScanCodesWindow):
        _translate = QtCore.QCoreApplication.translate
        ScanCodesWindow.setWindowTitle(_translate("ScanCodesWindow", "Form"))
        self.chooseFiles.setText(_translate("ScanCodesWindow", "Выбрать файлы для сканирования"))
        self.label.setText(_translate("ScanCodesWindow", "Тип кодов НС/ДС"))
        self.source.setItemText(1, _translate("ScanCodesWindow", "НС"))
        self.source.setItemText(2, _translate("ScanCodesWindow", "ДС"))
        self.scan.setText(_translate("ScanCodesWindow", "Сканировать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ScanCodesWindow = QtWidgets.QWidget()
    ui = Ui_ScanCodesWindow()
    ui.setupUi(ScanCodesWindow)
    ScanCodesWindow.show()
    sys.exit(app.exec_())
